### ISSUE TITLE
Construction du casier

### ISSUE THREAD

**Issue by NaoufalBen** [noo-name/3-minutes#38]
- [x] **2.4 - 2** Tester les matériaux de la structure du casier RÉUSSITE
- [x] **2.5 - 2** Tester les matériaux isolant pour les murs du casier RÉUSSITE 
- [x] **2.6 - 2** Achat des murs du casier
- [x] **2.7 - 2** Achat du devant du casier

**Comment by SamuelPoulin1** [comment]
**1.1 - 1** Les tuyaux pvc de une demie pouce de large sont trop petits et la structure est instable.
Solution: Utiliser des tuyaux pvc de 2 pouce de large à la place.

**Comment by SamuelPoulin1** [comment]
**1.1 - 2** Il est impossible de trouver des raccords pour tuyaux en magasin.
Solution: Modéliser en 3D les raccords et les imprimer à l'aide d'une imprimante 3D.

**Comment by jeremieLevesque** [comment]
La recherche des matériaux est compliqué mais pas impossible pour le momment j'ai été dans plusieurs sucursal de addtronic afin de trouver un détecteur aimenté pour l'activation de la lumière cependant il est back order partout ou je vais donc je vais le commander sur amazon ou ebay si je ne trouve pas de solution nous allons utilisés la knek afin d'ouvrir la lumière avec la détection de présence dans la zone du capteur.
