### ISSUE TITLE
Tester l'ambiance sonore du casier

### ISSUE THREAD

**Issue by NaoufalBen** [noo-name/3-minutes#39]
- [x] **2.3 - 2** Savoir à quelle distance de l’utilisateur les haut-parleurs seront placés, à quelles intensités sonores seront les haut-parleurs et comment placer les sons d’ambiance pour avoir un son 360 degrés.

**Comment by SamuelPoulin1** [comment]
**1.1 - 1** L'ambiance sonore a bien été créée dans Reaper.

**Comment by jeremieLevesque** [comment]
Tester dans le petit studio la disposition des 4 haut-parleurs afin de connaitre les distances a utilisés et quel niveau sonore utilisé pour être confortables.

**Comment by SamuelPoulin1** [comment]
**1.1 - 2** Les tests ont été réalisés dans le petit studio avec l'aide de Daryl. Tout fonctionne. Le son de la cloche est fort, mais peut être diminué facilement. L'exportation en quadriphonique fonctionne avec merveille. Ne pas oublier de choisir la bonne sortie audio!
