### ISSUE TITLE
Tests de lumière

### ISSUE THREAD

**Issue by NaoufalBen** [noo-name/3-minutes#42]
- [x] **2.1 - 2** Tester l'emplacement et l'angle de la lumière pour que lorsque que nous allons avoir le casier nous puissions le mettre en valeur sous la lumière. RÉUSSITE
- [x] **2.2 - 2** Il faut choisir la bonne intensité de lumière pour réussir à mettre en valeur l’élément que nous voulons éclairer. RÉUSSITE.

**Comment by SamuelPoulin1** [comment]
**1.1 - 1** Nous avons testé l'emplacement et l'angle de la lumière dans le grand studio le 7 décembre pendant le dinée avec l'aide de Guillaume. Elle sera en hauteur et pointera vers le sol (droite).

**Comment by SamuelPoulin1** [comment]
**1.1 - 2** (testé le 7 décembre également) La lumière sera blanche, car nous ne pouvons pas changer sa couleur. Cela n'est pas grave, car c'est la couleur désirée.

**Comment by SamuelPoulin1** [comment]
**1.1 - 3** (testé le 7 décembre également) L'intensité sera moyenne pour ne pas aveugler les personnes, mais pas trop faible pour être visible.
